// <auto-generated />
using System;
using MedPal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedPal.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109174000_Phase1EnumsInvoiceReportAuditLog")]
    partial class Phase1EnumsInvoiceReportAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // El contenido se genera automáticamente por EF Core
            // Este archivo representa la estructura después de la migración

#pragma warning restore 612, 618
        }
    }
}
